### ISSUE TITLE
Can't link too

### ISSUE THREAD

**Issue by ghost** [MiJyn/openlux#4]
I got your answer on your WP-site. I have the same errors.
Cheers Bernhard S.
![cmake](https://cloud.githubusercontent.com/assets/2652120/9843840/55e759e6-5abe-11e5-9992-0e67c5c7b1fb.png)
![undefined_references](https://cloud.githubusercontent.com/assets/2652120/9843841/55f399cc-5abe-11e5-96eb-559d2729f3f7.png)

**Comment by ghost** [comment]
I think you should try the latest version of this repository. I had the same issue #2 but now it's working

**Comment by ghost** [comment]
Hi, I tried it. Exactly the same 'make'-failure. Do I have another version of libX11?

**Comment by AnonymousMeerkat** [comment]
I just tried to build it on ubuntu, and, I've been able to finally replicate the bug!! It works on my end now, can you see if it works on yours too?

@Tankypon , before running `git pull`, you will probably have to run `git reset --hard HEAD` in order to reset the changes in the root CMakeLists.txt file (since git will complain otherwise) :)

**Comment by ghost** [comment]
Yes, it works. Thank you :-) There are five unused labels in main.c, btw. What was the problem?

**Comment by AnonymousMeerkat** [comment]
Yay!! The issue was that I was linking X11 _before_ the code that was needing it (instead of after). For some reason, this worked fine on void linux (the distribution I'm running), but it didn't on ubuntu.

About the unused labels, nothing to worry about. They're simply used as points to jump to if an error occurs (except that I haven't written code that requires jumping to the ones listed in the warnings) :) I'll disable the warning though, since, I agree, it's quite annoying =p

Thank you very much @bsbhro and @Tankypon for taking the time to report the bug and follow up on it!! (I'll leave this issue open in case @Tankypon has an issue with it)

**Comment by ghost** [comment]
@AnonymousMeerkat It's fine for me, the source code compiles ;)

**Comment by AnonymousMeerkat** [comment]
Awesome, one issue down!! :D
